<select name="prefectures">
  <option value="1" {if $selected == 1}selected{/if}>北海道</option>
  <option value="2" {if $selected == 2}selected{/if}>青森県</option>
  <option value="3" {if $selected == 3}selected{/if}>岩手県</option>
  <option value="4" {if $selected == 4}selected{/if}>宮城県</option>
  <option value="5" {if $selected == 5}selected{/if}>秋田県</option>
  <option value="6" {if $selected == 6}selected{/if}>山形県</option>
  <option value="7" {if $selected == 7}selected{/if}>福島県</option>
  <option value="8" {if $selected == 8}selected{/if}>茨城県</option>
  <option value="9" {if $selected == 9}selected{/if}>栃木県</option>
  <option value="10" {if $selected == 10}selected{/if}>群馬県</option>
  <option value="11" {if $selected == 11}selected{/if}>埼玉県</option>
  <option value="12" {if $selected == 12}selected{/if}>千葉県</option>
  <option value="13" {if $selected == 13}selected{/if}>東京都</option>
  <option value="14" {if $selected == 14}selected{/if}>神奈川県</option>
  <option value="15" {if $selected == 15}selected{/if}>新潟県</option>
  <option value="16" {if $selected == 16}selected{/if}>富山県</option>
  <option value="17" {if $selected == 17}selected{/if}>石川県</option>
  <option value="18" {if $selected == 18}selected{/if}>福井県</option>
  <option value="19" {if $selected == 19}selected{/if}>山梨県</option>
  <option value="20" {if $selected == 20}selected{/if}>長野県</option>
  <option value="21" {if $selected == 21}selected{/if}>岐阜県</option>
  <option value="22" {if $selected == 22}selected{/if}>静岡県</option>
  <option value="23" {if $selected == 23}selected{/if}>愛知県</option>
  <option value="24" {if $selected == 24}selected{/if}>三重県</option>
  <option value="25" {if $selected == 25}selected{/if}>滋賀県</option>
  <option value="26" {if $selected == 26}selected{/if}>京都府</option>
  <option value="27" {if $selected == 27}selected{/if}>大阪府</option>
  <option value="28" {if $selected == 28}selected{/if}>兵庫県</option>
  <option value="29" {if $selected == 29}selected{/if}>奈良県</option>
  <option value="30" {if $selected == 30}selected{/if}>和歌山県</option>
  <option value="31" {if $selected == 31}selected{/if}>鳥取県</option>
  <option value="32" {if $selected == 32}selected{/if}>島根県</option>
  <option value="33" {if $selected == 33}selected{/if}>岡山県</option>
  <option value="34" {if $selected == 34}selected{/if}>広島県</option>
  <option value="35" {if $selected == 35}selected{/if}>山口県</option>
  <option value="36" {if $selected == 36}selected{/if}>徳島県</option>
  <option value="37" {if $selected == 37}selected{/if}>香川県</option>
  <option value="38" {if $selected == 38}selected{/if}>愛媛県</option>
  <option value="39" {if $selected == 39}selected{/if}>高知県</option>
  <option value="40" {if $selected == 40}selected{/if}>福岡県</option>
  <option value="41" {if $selected == 41}selected{/if}>佐賀県</option>
  <option value="42" {if $selected == 42}selected{/if}>長崎県</option>
  <option value="43" {if $selected == 43}selected{/if}>熊本県</option>
  <option value="44" {if $selected == 44}selected{/if}>大分県</option>
  <option value="45" {if $selected == 45}selected{/if}>宮崎県</option>
  <option value="46" {if $selected == 46}selected{/if}>鹿児島県</option>
  <option value="47" {if $selected == 47}selected{/if}>沖縄県</option>
  <option value="99" {if $selected == 99}selected{/if}>その他</option>
</select><!-- name=prefectures -->
